// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABFq85bV3nYPIFHn0f2k6NAbuhhnV2v4U',
    appId: '1:753361687757:web:ab875623474765df7c4584',
    messagingSenderId: '753361687757',
    projectId: 'skillswap-4537a',
    authDomain: 'skillswap-4537a.firebaseapp.com',
    storageBucket: 'skillswap-4537a.firebasestorage.app',
    measurementId: 'G-73LQPR5CDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEgh_gDhH5Z31hny1nKZsq62i0OtiAP48',
    appId: '1:753361687757:android:a3744b874dcb81ce7c4584',
    messagingSenderId: '753361687757',
    projectId: 'skillswap-4537a',
    storageBucket: 'skillswap-4537a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOJH7MHtwWwUF2jTLyXBmEWYss5_2gVWY',
    appId: '1:753361687757:ios:ec635697d021ed957c4584',
    messagingSenderId: '753361687757',
    projectId: 'skillswap-4537a',
    storageBucket: 'skillswap-4537a.firebasestorage.app',
    iosBundleId: 'com.example.websocket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOJH7MHtwWwUF2jTLyXBmEWYss5_2gVWY',
    appId: '1:753361687757:ios:ec635697d021ed957c4584',
    messagingSenderId: '753361687757',
    projectId: 'skillswap-4537a',
    storageBucket: 'skillswap-4537a.firebasestorage.app',
    iosBundleId: 'com.example.websocket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABFq85bV3nYPIFHn0f2k6NAbuhhnV2v4U',
    appId: '1:753361687757:web:0375ee9e44bcabf07c4584',
    messagingSenderId: '753361687757',
    projectId: 'skillswap-4537a',
    authDomain: 'skillswap-4537a.firebaseapp.com',
    storageBucket: 'skillswap-4537a.firebasestorage.app',
    measurementId: 'G-RZ6PNV7PE2',
  );
}
